name: Python Application CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with pylint
      run: |
        pylint . || true

    - name: Run unit tests
      run: |
        python -m unittest discover tests

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: nidhimaa/calculator-app:latest

    - name: Simulate Jira update
      run: |
        echo "Running dummy Jira integration script"
        if [ -f jira/jira_integration.py ]; then python jira/jira_integration.py; fi

    - name: Prepare Kubernetes deployment
      run: |
        echo "Simulating deployment to Kubernetes"
        if [ -f kubernetes/deployment.yaml ]; then cat kubernetes/deployment.yaml; fi

    - name: Prepare Ansible deployment
      run: |
        echo "Simulating Ansible run"
        if [ -f ansible/playbook.yml ]; then cat ansible/playbook.yml; fi
